# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0014_contacted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('mobile_no', models.IntegerField()),
                ('pan_no', models.CharField(max_length=10)),
                ('Occupation', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Self', 'Self-Employed')], default='Public', max_length=7)),
                ('contacted_properties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_prop_user', to='property.PropertyTable')),
                ('listed_properties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_prope_user', to='property.PropertyTable')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
