# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 05:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('issue_type', models.CharField(choices=[('SELL', 'Selling a property'), ('BUY', 'Buying Related'), ('CONTACT', 'Contacting Seller or Buyer')], default='CONTACT', max_length=7)),
                ('issue', models.TextField(max_length=256)),
                ('bot_field', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=30)),
                ('property_address', models.CharField(max_length=60)),
                ('property_age', models.IntegerField(default=0)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('unit/flat', 'Flat'), ('Townhouse', 'Villa')], default='House', max_length=9)),
                ('property_pincode', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=property.models.upload_property_images)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('property_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='property.PropertyTable')),
                ('property_area', models.IntegerField()),
                ('property_bedroom', models.IntegerField()),
                ('property_parking', models.BooleanField(choices=[(True, 'Available'), (False, 'Not Available')], default=True, max_length=9)),
                ('property_buid_year', models.DateField(default=datetime.date(1950, 12, 12))),
                ('property_facing', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], default='N', max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='propertytable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
