# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytable',
            old_name='user',
            new_name='user_data',
        ),
    ]
