# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='proprty_location',
            new_name='property_address',
        ),
        migrations.AddField(
            model_name='property',
            name='property_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='property_pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('unit/flat', 'Flat'), ('Townhouse', 'Villa')], default='House', max_length=9),
        ),
        migrations.AddField(
            model_name='property',
            name='property_updated',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 1, 30, 6, 45, 42, 492345, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
