# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190130_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_added',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_updated',
        ),
        migrations.AddField(
            model_name='property',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
