# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190313_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytable',
            name='property_price',
            field=models.IntegerField(default=0),
        ),
    ]
