# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertytable_property_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytable',
            old_name='property_age',
            new_name='property_rooms',
        ),
        migrations.AddField(
            model_name='propertytable',
            name='property_location',
            field=models.CharField(choices=[('North', 'Northern Metropoliton'), ('South', 'Southern Metropoliton'), ('East', 'Eastern Metropoliton'), ('West', 'Western Metropoliton')], default='North', max_length=5),
        ),
    ]
