# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20190314_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytable',
            name='image',
            field=models.ImageField(upload_to=property.models.upload_property_images),
        ),
    ]
