# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20190319_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytable',
            name='property_rooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=2),
        ),
    ]
