# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20190130_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='registration_doc',
            field=models.FileField(blank=True, null=True, upload_to='property/registration_doc'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_deed_image',
            field=models.ImageField(blank=True, null=True, upload_to='property/images'),
        ),
    ]
