# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20190319_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='property_id',
        ),
        migrations.AddField(
            model_name='propertytable',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=property.models.upload_property_images2),
        ),
        migrations.AddField(
            model_name='propertytable',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=property.models.upload_property_images3),
        ),
        migrations.AlterField(
            model_name='propertytable',
            name='property_location',
            field=models.CharField(choices=[('East', 'Amanora'), ('West', 'Aundh'), ('South', 'Balaji nagar'), ('West', 'Baner'), ('West', 'Bavdhan'), ('South', 'Bibwewadi'), ('East', 'Fatima nagar'), ('North', 'Gokul nagar'), ('East', 'Hadapsar'), ('North', 'Kalyani nagar'), ('East', 'Karadhi'), ('South', 'Katraj'), ('South', 'Kondhwa'), ('West', 'Kothrud'), ('West', 'Lavale'), ('North', 'Lohegoan'), ('East', 'Magarpatta'), ('East', 'Modi colony'), ('South', 'Nanded'), ('West', 'Pashan'), ('West', 'Paud'), ('East', 'Pune contonment'), ('North', 'Ram wadi'), ('South', 'Sai nagar'), ('North', 'Shanti nagar'), ('North', 'Viman Nagar'), ('North', 'Yerawada')], default='North', max_length=5),
        ),
        migrations.DeleteModel(
            name='PropertyDetails',
        ),
    ]
