# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import property.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20190131_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('property_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='property.Property')),
                ('property_area', models.IntegerField()),
                ('property_bedroom', models.IntegerField()),
                ('property_parking', models.CharField(choices=[(True, 'Available'), (False, 'Not Available')], default=True, max_length=9)),
                ('property_buid_year', models.DateField(default=datetime.date(1950, 12, 12))),
                ('property_facing', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], default='N', max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='registration_doc',
            field=models.FileField(blank=True, null=True, upload_to=property.models.upload_property_reg),
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_deed_image',
            field=models.ImageField(blank=True, null=True, upload_to=property.models.upload_property_sale),
        ),
    ]
