# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20190131_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='property_parking',
            field=models.BooleanField(choices=[(True, 'Available'), (False, 'Not Available')], default=True, max_length=9),
        ),
    ]
