# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20190131_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Owner_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=256)),
                ('phno', models.IntegerField(max_length=10)),
                ('Address', models.TextField(max_length=144)),
                ('age', models.IntegerField()),
                ('pan_no', models.CharField(max_length=10)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PropertyTable')),
            ],
        ),
    ]
