# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_property_owner_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_owner_details',
            name='phno',
            field=models.IntegerField(),
        ),
    ]
