# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('issue_type', models.CharField(choices=[('SELL', 'Selling a property'), ('BUY', 'Buying Related'), ('CONTACT', 'Contacting Seller or Buyer')], default='CONTACT', max_length=7)),
                ('issue', models.TextField(max_length=256)),
                ('bot_field', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
